---
title: "Research"
pagetitle: "Research - Julio Garbers"
---

## Publications

::: {.paper}
### Citizenship and Integration {.paper-title}

::: {.paper-meta}
with [Christina Gathmann (LISER)](https://sites.google.com/view/christina-gathmann/start){target="_blank"}<br>
*Labour Economics*, Vol. 82, June 2023, 102343
:::

::: {.paper-abstract}
Several European countries have reformed their citizenship policies over the past decades. There is much to learn from their experience of how citizenship works; for whom it works; and what rules and policies matter for integration. The article surveys recent quasi-experimental evidence and field experiments from the social sciences on the link between eligibility rules, take-up and integration outcomes. Across countries and reforms, the evidence shows that faster access to citizenship increases take-up and improves the economic, educational, political and social integration of immigrants. Other eligibility rules like civic knowledge tests or application fees also impact who naturalizes and therefore benefits from citizenship. Birthright citizenship, which is much less common in Europe, turns out to be a powerful tool for getting second-generation immigrants off to a good start. Together, citizenship acts as a powerful catalyst benefiting immigrants as well as host countries.
:::

::: {.paper-links}
[Published Version](https://www.sciencedirect.com/science/article/pii/S0927537123000180){.paper-link target="_blank"}
[Working Paper](https://www.iza.org/publications/dp/15786/citizenship-and-integration){.paper-link target="_blank"}
:::
:::

## Working Papers / Work in Progress

::: {.paper}
### Arriving LATE: Access to Citizenship and Economic Integration {.paper-title}

::: {.paper-meta}
with [Christina Gathmann (LISER)](https://sites.google.com/view/christina-gathmann/start){target="_blank"}
:::

::: {.paper-abstract}
We analyze whether faster access to citizenship fosters the economic integration of immigrants. Our empirical setting is Germany, which went from a strict concept of citizenship based on 'jus sanguinis' to a more open citizenship policy. We make use of discontinuities in residency requirements faced by first-generation immigrants to estimate LATEs based on Local Randomization and Fuzzy RDD approaches. We find that a more liberal citizenship policy acts as a catalyst for integration, especially for immigrant women. Women's labor force participation increases by 8.9 percentage points and their earnings by 21.3%. We do not find any significant effects on immigrant men.
:::
:::

::: {.paper}
### Small Pictures, Big Biases: The Adverse Effect of an Airbnb Design Intervention {.paper-title}

::: {.paper-meta}
with [Carlotta Montorsi (LISER)](https://carlottamnt.github.io/){target="_blank"}
:::

::: {.paper-abstract}
A 2018 Airbnb design intervention reduced the size of the host profile picture, creating a natural experiment to test whether the salience of visual cues affects racial bias in the demand for Airbnb listings. Using scraped data from Airbnb in New York City and a face classification model, we find that, unexpectedly, the new design increased the Black-White demand disparity by 3.3 percentage points, an increase of about 30% relative to the pre-intervention gap. We show that smaller images made it harder for guests to detect positive facial cues – especially smiles – that are typically associated with higher demand, leading them to rely more heavily on skin color. In response, Black hosts updated their profile pictures to make their faces more visible and added basic amenities to their listings.
:::
:::

::: {.paper}
### The Diffusion of Artificial Intelligence Across Firms: Evidence from Europe {.paper-title}

::: {.paper-meta}
with [Terry Gregory (LISER)](https://sites.google.com/view/terrygregory){target="_blank"}
:::

::: {.paper-abstract}
We develop a novel firm-level indicator of Artificial Intelligence adoption in Europe (MAP-AI) by extracting information on AI usage from more than three million firm websites from Belgium, France, Germany, and Luxembourg (2016–2024) using a Large Language Model. The indicator captures realized AI adoption as signaled on their website rather than potential exposure. Our method allows to detect not only whether firms adopt AI, but also their role in the AI ecosystem and the type of AI technology they employ. Validation against human-coded benchmarks and external referenecs confirms high accuracy and external validity. We find that the share of AI-active firms grew from 1% in 2016 to 12% in 2024, with acceleration after 2022. We document a structural transformation in the AI ecosystem, as expanding AI adoption increases the share of adopters in overall AI activity, signaling widespread diffusion and more integrated AI use, including generative AI. While adoption is concentrated among larger, younger, knowledge-intensive firms in urban innovation clusters, workforce skills emerge as a key factor associated with AI adoption. Our skill-level analysis shows that foundational data skills form a necessary base for adoption, while a small set of specialized AI skills – such as machine learning and natural language processing – act as strong complements, highlighting human capital as a central driver of AI diffusion across firms.
:::

::: {.paper-links}
[Data Repository](https://github.com/MAP-AI-data/data){.paper-link target="_blank"}
:::
:::